### ISSUE TITLE
Is it possible to use facebook native and facebook native banner in one app using placer for loading ads?

### ISSUE THREAD

**Issue by geraldika** [mopub/mopub-android-mediation#317]
1. **What is the issue?**
    > Provide a one-line summary of the issue here.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
    * **Ad Format** (*Banner, Interstitial, Rewarded Video, Native Static, Native Video*)
        > Provide the data here
    * **Platform** (*Android, iOS, Unity*)
        > Provide the data here
    * **MoPub SDK Version**
        > Provide the data here
    * **Mediation SDK Name & Version**
        > Provide the data here
    * **Mediation Adapter Version**
        > Provide the data here
    * **MoPub Ad Unit ID(s) used to reproduce the issue**
        > Provide the data here
    * **Device model and OS Version**
        > Provide the data here
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Do this.
        > 2. Do that.
    * **Observed behavior**
        > Provide the data here
    * **Expected behavior** (if known)
        > Provide the data here
    * **Evidence** (if available)
        > Attach logs (device/network), mini debug builds (source code preferably), stack traces, screenshots / screen recordings, etc.

**Comment by chauduyphanvu** [comment]
@geraldika, because the ad placer requires a [native banner flag](https://developers.mopub.com/publishers/mediation/networks/facebook/#android-ad-placer-integration) to be set when you initialize MoPub, you can only change your preference once per app session. That means that once you have set the ad type as native banner, the ad placer will request only native banner until you reset the flag, which happens when you next launch the app and initialize MoPub. With the present design, it is not possible to request both native and native banner via the ad placer in one app session.

For flexibility, you may consider using `MoPubNative` and [setting the flag via `localExtras`](https://developers.mopub.com/publishers/mediation/networks/facebook/#android-manual-native-ad-integration). This way, you can reset the flag as often as in every ad request (without having to relaunch the app and reinitialize MoPub).

Vu Chau
MoPub Team
