### ISSUE TITLE
FAN native ads clickable everywhere?

### ISSUE THREAD

**Issue by vunhiem96** [mopub/mopub-android-mediation#368]
When using Fan's SDK only positions like CTA,Title,Icon can be clicked, but when I switch to Bidding of Mopub, when i test with Fan, I can click everywhere, this will lead to many invalid clicks

Use: com.mopub:mopub-sdk:5.17
'com.mopub.mediation:facebookaudiencenetwork:6.4.0.0'

**Comment by hoanghiephui** [comment]
@chauduyphanvu can you help me.

**Comment by chauduyphanvu** [comment]
@vunhiem96, you need to adjust your XML layout so that each ad asset is strictly wrapped (use `wrap_content`). Do not use `match_parent` or give it a width larger than necessary. The reason is that any spaces not occupied by the ad are still part of the view for that ad asset, and so they will still be clickable. 

You can reference our sample app ad layout at https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sample/res/main/layout/native_ad_fan_list_item.xml. Let us know if there are any questions.

Vu Chau
MoPub Team
